### ISSUE TITLE
Stop updating

### ISSUE THREAD

**Issue by LucMacPaquet** [Jopyth/MMM-Trello#10]
Hi

First, thanks for your module. Very useful. 

I notice that after a while(can't tell how long), changes made on Trello website are not synched to the mirror.

Any idea where to look to troubleshoot that?

Thanks

**Comment by Jopyth** [comment]
If you have not found out yet: You could look at the output of the mirror, e.g. `pm2 logs MagicMirror`.

**Comment by guillaumesoul** [comment]
same problem, the synched stop between 12 and 24 hours after the start in my case, I can't tell preciseley when

**Comment by dasam** [comment]
seems i ran into this aswell, after 1 week it stops updating for me. Now trying to force a update interval to see if it solves the problem.

**Comment by johnkjellberg** [comment]
I have the same problem. The only thing I can find in the logs are:

```
{ Error: getaddrinfo EAI_AGAIN api.trello.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.trello.com',
  host: 'api.trello.com',
  port: 443 }
{ Error: getaddrinfo EAI_AGAIN api.trello.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.trello.com',
  host: 'api.trello.com',
  port: 443 }
```

**Comment by geronimodupree** [comment]
Any workarounds for this? I have errors similar to log posted by @johnkjellberg

**Comment by etcho** [comment]
Same thing here.
