### ISSUE TITLE
Checklist loading forever

### ISSUE THREAD

**Issue by wast** [Jopyth/MMM-Trello#12]
Got 2 cards in a list. Both cards are loaded on mirror and both have a checklist but only 1 checklist is loaded.  The other one shows loading icon.

**Comment by Jopyth** [comment]
I am not sure, but I also do not have much time to work on this currently.

**Comment by aandrew7** [comment]
I've Got 1 cards in a list. Mirror just shows loading icon.

**Comment by aandrew7** [comment]
I rebooted and it worked

**Comment by nahtnam** [comment]
I have the same issue. I have a trello list with 7 cards, one day for each week, and I enabled `wholeList`, but it just shows the loading icon for all 7 cards forever.

**Comment by wast** [comment]
@Jopyth any ways we can try to debug it? What should we be looking at?

**Comment by Jopyth** [comment]
Is there anything in the logs (usually `pm2 logs MagicMirror` (or `mm` if you have the old version)?

**Comment by o-shabashov** [comment]
Yes, I got these in logs:
```
TypeError: Cannot read property ‘hash’ of null
at /home/pi/MagicMirror/modules/default/updatenotification/node_helper.js:68:31
at Git. (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1482:10)
at done (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1354:21)
at ChildProcess. (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1379:16)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

**Comment by wangxum168** [comment]
@wast 
In my case, it depends on the “reloadInterval” in the config file. For example, the defualt reload interval is 10min. Then, "checklist" will load  after you start server. The problem is that checklist does not load immediately, but load after the first reload interval. You can change  “reloadInterval” to 5 or 10 sec and see the results. Hope this helps :) This is my favourate mm module!

**Comment by wast** [comment]
@wangxum168 I think it wasn't the case because I tried leaving it over night and didn't load.
@Jopyth How to check logs when running server only? (Pi W Zero)

**Comment by felipemfa** [comment]
I have the same problem, loading forever. in browser console I Got this error:
`Uncaught TypeError: console.log is not a function
    at Class.socketNotificationReceived (MMM-Trello.js:263)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)`

**Comment by dewmguy** [comment]
I have the same problem as well. however, @wangxum168 was correct, if you wait long enough it will eventually load the checklists on the next interval. Is there a way to make this load with the page the first time instead of changing the interval time?
