### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by greedyvegan** [Jopyth/MMM-Trello#35]
followed every step and landed this 
<img width="638" alt="Screenshot 2024-04-01 at 3 18 58 PM" src="https://github.com/Jopyth/MMM-Trello/assets/128918275/e602c12a-a728-4799-8884-9f6a92cc9540">

**Comment by Wdave40** [comment]
I have that too. Did you resolve it?

**Comment by TrueSolara** [comment]
My setup worked three months ago, but now I'm getting the same.

**Comment by Jopyth** [comment]
I also saw this error. Unfortunately, I do not have time to continue the development of this module in the foreseeable future. I have disabled my Trello module on our MM², as we did not use it a lot anymore.

It seems Trello has changed their API access key structure from what I can see [here](https://trello.com/app-key). Maybe this is the reason?

If someone wants to continue developing this module, let me know. I could archive this repository and link to their updated version.

**Comment by Wdave40** [comment]
Thanks Jopyth. Wish I had the skills. If someone does pick it up please message on here. I'd love to get it working again.

**Comment by benjaminflessner** [comment]
Per https://developer.atlassian.com/cloud/trello/changelog/ as of  March 12, 2024, GET requests will no longer work with content in the body.

Since https://github.com/adunkman/node-trello is also defunct, I have (for now) just gone into `node_modules/node-trello/lib/node-trello.js` and modified [line 83](https://github.com/adunkman/node-trello/blob/3975309f91b7153ca11e7028975d40353ba2a5d7/lib/node-trello.js#L83):

```
  else {
    options.json = true; // tells request to return json
    // options.json = this.addAuthArgs(this.parseQuery(uri, args));
  }
```

~That gets me past the 403. (I'm still getting undefined for my card display; but I'm still playing around with this module)~

Instead of commenting out the line; just set `options.json = true;` and things seem to work again! Without it, the body is returned as a string, and the module cannot process it.

**Comment by jaxfellow** [comment]
> Per https://developer.atlassian.com/cloud/trello/changelog/ as of March 12, 2024, GET requests will no longer work with content in the body.
> 
> Since https://github.com/adunkman/node-trello is also defunct, I have (for now) just gone into `node_modules/node-trello/lib/node-trello.js` and modified [line 83](https://github.com/adunkman/node-trello/blob/3975309f91b7153ca11e7028975d40353ba2a5d7/lib/node-trello.js#L83):
> 
> ```
>   else {
>     options.json = true; // tells request to return json
>     // options.json = this.addAuthArgs(this.parseQuery(uri, args));
>   }
> ```
> 
> ~That gets me past the 403. (I'm still getting undefined for my card display; but I'm still playing around with this module)~
> 
> Instead of commenting out the line; just set `options.json = true;` and things seem to work again! Without it, the body is returned as a string, and the module cannot process it.

Unfortunately, it didn't work for me
```
[2025-10-11 18:23:06.738] [LOG]   Error: model not found
    at Request._callback (/opt/magicmirror/modules/MMM-Trello/node_modules/node-trello/lib/node-trello.js:88:13)
    at self.callback (/opt/magicmirror/modules/MMM-Trello/node_modules/request/request.js:185:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/opt/magicmirror/modules/MMM-Trello/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/opt/magicmirror/modules/MMM-Trello/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  statusCode: 404,
  responseBody: 'model not found',
  statusMessage: 'Not Found'
```
